# Generated by Django 3.1.7 on 2021-03-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaAkun', models.CharField(max_length=200, null=True)),
                ('coaAwal', models.CharField(max_length=200, null=True)),
                ('coaAkun', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cabang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaCabang', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomorDokumen', models.CharField(max_length=200, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('desc', models.CharField(max_length=400, null=True)),
                ('tipeAkun', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=200, null=True)),
                ('price', models.FloatField(default=0, max_length=100)),
                ('saldoCredit', models.FloatField(default=0, max_length=100)),
                ('saldoDebit', models.FloatField(default=0, max_length=100)),
                ('akun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akuntabelapp.akun')),
                ('cabang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akuntabelapp.cabang')),
            ],
        ),
    ]
