# Generated by Django 3.0 on 2021-03-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuntabelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaksi',
            old_name='saldoCredit',
            new_name='saldoCredit1',
        ),
        migrations.RenameField(
            model_name='transaksi',
            old_name='saldoDebit',
            new_name='saldoCredit2',
        ),
        migrations.AddField(
            model_name='transaksi',
            name='saldoCredit3',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='saldoCredit4',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='saldoCredit5',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='saldoCredit6',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='saldoCredit7',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='saldoCredit8',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='saldoCredit9',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='saldoDebit1',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='saldoDebit2',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='saldoDebit3',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='saldoDebit4',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='saldoDebit5',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='saldoDebit6',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='saldoDebit7',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='saldoDebit8',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='saldoDebit9',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
